#
# make        Run latex and generate new pdf document
# make gif    Generate gifs of everything in eps directory
# make clean  Delete the LaTeX junk files (rm *.aux *.dvi *.log)
#
# Doug Wright

file = fission_usermanual.tex

include macros/Makefile
